import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: "class",
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#fb5151",
        "secondary": "#006b1c",
        "on-surface": "#2a2f32",
        "primary-fixed-dim": "#42b9ed",
        "on-primary-container": "#003d54",
        "tertiary-container": "#fdd34d",
        "primary-dim": "#005673",
        "secondary-dim": "#005d17",
        "surface-bright": "#f3f7fb",
        "tertiary-dim": "#624d00",
        "outline": "#73777b",
        "surface": "#f3f7fb",
        "secondary-fixed": "#9af896",
        "error": "#b31b25",
        "on-background": "#2a2f32",
        "on-primary": "#e6f5ff",
        "on-error": "#ffefee",
        "inverse-on-surface": "#999da1",
        "on-surface-variant": "#575c60",
        "surface-container": "#e3e9ee",
        "tertiary-fixed-dim": "#eec540",
        "primary-container": "#54c7fc",
        "background": "#f3f7fb",
        "surface-dim": "#ced5db",
        "on-error-container": "#570008",
        "primary": "#006384",
        "surface-container-high": "#dde3e8",
        "surface-container-low": "#ecf1f6",
        "inverse-surface": "#0a0f12",
        "surface-tint": "#006384",
        "on-secondary-fixed-variant": "#006b1c",
        "outline-variant": "#a9aeb1",
        "surface-container-highest": "#d7dee3",
        "on-primary-fixed": "#002636",
        "on-secondary-fixed": "#004a11",
        "on-secondary-container": "#006018",
        "secondary-container": "#9af896",
        "on-tertiary-container": "#5c4900",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#8cea8a",
        "tertiary-fixed": "#fdd34d",
        "tertiary": "#705900",
        "inverse-primary": "#54c7fc",
        "on-tertiary-fixed-variant": "#675200",
        "primary-fixed": "#54c7fc",
        "on-primary-fixed-variant": "#004760",
        "on-secondary": "#d1ffc9",
        "on-tertiary": "#fff2d4",
        "error-dim": "#9f0519",
        "on-tertiary-fixed": "#463600",
        "surface-variant": "#d7dee3"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        headline: ['var(--font-jakarta)', 'sans-serif'],
        body: ['var(--font-lexend)', 'sans-serif'],
        label: ['var(--font-lexend)', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms'),
  ],
};

export default config;
